# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kivo < Formula
  desc ""
  homepage "https://github.com/Permify/kivo"
  version "0.0.5"
  license "Apache-2.0"

  depends_on "go" => :build

  on_macos do
    url "https://github.com/Permify/kivo/releases/download/v0.0.5/kivo_0.0.5_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "7d7c716233e0dd18996f8f778a956fc6ae6395c0eaf913a69790387cee22e758"

    def install
      bin.install "kivo"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Permify/kivo/releases/download/v0.0.5/kivo_0.0.5_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "d456a2a2387c3d81d173ca408454df8624db7c74ea1724afea6bdf346149a692"

        def install
          bin.install "kivo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Permify/kivo/releases/download/v0.0.5/kivo_0.0.5_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "1e5363c987bfe7592978508c213d85d7e85daec9dc1770dd734433bf807449ce"

        def install
          bin.install "kivo"
        end
      end
    end
  end

  head "https://github.com/Permify/kivo.git", :branch => "master"
end
