# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kivo < Formula
  desc ""
  homepage "https://github.com/Permify/kivo"
  version "0.0.4"
  license "Apache-2.0"

  depends_on "go" => :build

  on_macos do
    url "https://github.com/Permify/kivo/releases/download/v0.0.4/kivo_0.0.4_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "83f5304361581fef3817680a654910a01629f49ab353cdf1157352cdf119d2a4"

    def install
      bin.install "kivo"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Permify/kivo/releases/download/v0.0.4/kivo_0.0.4_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "ae1d08ad9bb1de60a5f32a4e41214550d600e32f73198db5a9ace01ba661daaa"

        def install
          bin.install "kivo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Permify/kivo/releases/download/v0.0.4/kivo_0.0.4_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "9a5e1052d4ae246a9344c7cefe128871a84f7e7d5a4f03633bb1c9ba2a3a00fd"

        def install
          bin.install "kivo"
        end
      end
    end
  end

  head "https://github.com/Permify/kivo.git", :branch => "master"
end
