# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kivo < Formula
  desc ""
  homepage "https://github.com/Permify/kivo"
  version "0.1.0"
  license "Apache-2.0"

  depends_on "go" => :build

  on_macos do
    url "https://github.com/Permify/kivo/releases/download/v0.1.0/kivo_0.1.0_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "9fa3f9faf0e9349647ef71dbbd7150b92eb537303ff05e807172d27d7a263dab"

    def install
      bin.install "kivo"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Permify/kivo/releases/download/v0.1.0/kivo_0.1.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "a9d11cf546e33345469a5739bf6572e70be032dd4fd38a5b5b680b79ee4e8873"

        def install
          bin.install "kivo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Permify/kivo/releases/download/v0.1.0/kivo_0.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "78bd51fda56235a95333840dee385085796370fa961faf0411d4b27ca28cfbd5"

        def install
          bin.install "kivo"
        end
      end
    end
  end

  head "https://github.com/Permify/kivo.git", :branch => "master"
end
